language: python

jobs:
  include:
    - os: linux
    - os: osx
      language: generic
      env: TOXENV=py37
    - os: osx
      language: generic
      env: TOXENV=py38

python:
  - "3.7"
  - "3.8"

install:
  - ./.travis/install.sh
  - pip install --upgrade pip
  - pip install -r requirements.txt

script:
  - pytest -W ignore::DeprecationWarning